export enum ColorsEnum {
  black = 'black',
  red = 'red',
  green = 'green',
  blue = 'blue',
  yellow = 'yellow',
  orange = 'orange',
  purple = 'purple',
  pink = 'pink',
  brown = 'brown',
  gray = 'gray',
  lightGray = 'lightGray',
  darkGray = 'darkGray',
  cyan = 'cyan',
  magenta = 'magenta',
  maroon = 'maroon',
  olive = 'olive',
  navy = 'navy',
  teal = 'teal'
}